export const productsData = [
  {
    id: 1,
    title: "موبایل اپل مدل iPhone 13",
    price: 52439000,
    imageURL: "../Accets/images/iphone-13.png",
    Specifications: {
      speaker: "اسپیکر / استریو ( دوگانه )",
      ram: "رم / 4 گیگابایت رم",
      camera: "دوربین اصلی / 12 مگاپیکسل",
      storage: "حافظه داخلی / 256 گیگابایت",
      battery: "باتری / 3240 میلی آمپر ساعت",
    },
  },
  {
    id: 2,
    title: "پارتی باکس",
    price: 5200000,
    imageURL: "../Accets/images/Mingo-Party-Box.png",
    Specifications: {
      speaker: "ابعاد اسپیکر / 290x260x670",
      ram: "میکروفون / دارد",
      camera: "رقص نور / دارد",
      storage: "نوع حافظه / حافظه داخلی فلش",
      battery: "کارکرد باتری / 6 ساعت",
    },
  },
  {
    id: 3,
    title: " موبایل سامسونگ Galaxy s21",
    price: 37199000,
    imageURL: "../Accets/images/galaxy-s21.png",
    Specifications: {
      speaker: "اسپیکر / استریو ( دوگانه )",
      ram: "رم / 8 گیگابایت رم",
      camera: "دوربین اصلی / 12 مگاپیکسل",
      storage: "حافظه داخلی / 256 گیگابایت",
      battery: "باتری / 4000 میلی آمپر ساعت",
    },
  },
  {
    id: 4,
    title: "هدفون بی سیم AirPods Pro",
    price: 5795000,
    imageURL: "../Accets/images/airpod-pros-removebg-preview.png",
    Specifications: {
      speaker: "نوع اتصال / بی سیم",
      ram: "رنگ / سفید",
      camera: "میکروفون / دارد ",
      storage: "کنترل کننده صدا / دارد",
      battery: "طریقه شارژ / از طریق محفظه",
    },
  },
  {
    id: 5,
    title: "موبایل اپل مدل iPhone 14",
    price: 48000000,
    imageURL: "../Accets/images/iphone-14.png",
    Specifications: {
      speaker: "اسپیکر / استریو ( دوگانه )",
      ram: "رم / 6 گیگابایت رم",
      camera: "دوربین اصلی / 12 مگاپیکسل",
      storage: "حافظه داخلی / 512 گیگابایت",
      battery: "باتری / 3279 میلی آمپر ساعت",
    },
  },
  {
    id: 6,
    title: "موبایل شیائومی مدل Poco M4",
    price: 6799000,
    imageURL: "../Accets/images/poco-m4.webp",
    Specifications: {
      speaker: "اسپیکر / استریو ( دوگانه )",
      ram: "رم / 8 گیگابایت رم",
      camera: "دوربین اصلی / 50 مگاپیکسل",
      storage: "حافظه داخلی / 128 گیگابایت",
      battery: "باتری / 5000 میلی آمپر ساعت",
    },
  },
  {
    id: 7,
    title: "کنسول بازی Playstation 5",
    price: 23079200,
    imageURL: "../Accets/images/Playstation-5.webp",
    Specifications: {
      speaker: "پردازنده اصلی / 8 هسته ای ذن",
      ram: "رم / 16 گیگابایت GDDR6",
      camera: "خروجی تصویر / 4K - 8K",
      storage: "حافظه / 825 گیگابایت SSD",
      battery: "پشتیبانی از هارد اکسترنال / دارد",
    },
  },
  {
    id: 8,
    title: "موبایل سامسونگ Galaxy A51",
    price: 8200000,
    imageURL: "../Accets/images/galaxy-A51.png",
    Specifications: {
      speaker: "اسپیکر / مونو",
      ram: "رم / 6 گیگابایت رم",
      camera: "دوربین اصلی / 48 مگاپیکسل",
      storage: "حافظه داخلی / 128 گیگابایت",
      battery: "باتری / 4000 میلی آمپر ساعت",
    },
  },
];